# Generated by Django 5.1.4 on 2025-01-02 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_budget_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(default='Miscellaneous', max_length=100),
        ),
    ]
